[package]
name = "udap-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Command-line tool for configuring Squeezebox devices over UDAP"

[[bin]]
name = "udapcfg"
path = "src/main.rs"

[dependencies]
udap = { path = "../udap" }
anyhow.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "time"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
mocksbr = { path = "../mocksbr" }
insta.workspace = true

[lints]
workspace = true
