//! The `discover` subcommand.

use crate::{CliError, ClientFactory};
use std::io::Write;
use std::time::Duration;
use tokio_util::sync::CancellationToken;

/// Discovers devices and prints one MAC per line.
///
/// Finding nothing is not an error: a note goes to stderr and the exit
/// code stays 0, matching go-udap.
///
/// # Errors
/// [`CliError`] with code 2 if the client cannot be built or discovery fails.
pub async fn run(
    make_client: ClientFactory,
    timeout: Duration,
    stdout: &mut dyn Write,
    stderr: &mut dyn Write,
) -> Result<(), CliError> {
    let mut client = make_client().map_err(|e| CliError { code: 2, source: e })?;

    let cancel = CancellationToken::new();
    let token = cancel.clone();
    tokio::spawn(async move {
        tokio::time::sleep(timeout).await;
        token.cancel();
    });

    client.discover(&cancel).await.map_err(|e| CliError {
        code: 2,
        source: anyhow::Error::new(e).context("discovery failed"),
    })?;

    let devices = client.devices();
    if devices.is_empty() {
        let _ = writeln!(
            stderr,
            "no devices found within {}",
            format_duration(timeout)
        );
        return Ok(());
    }
    for device in devices {
        let _ = writeln!(stdout, "{}", device.mac);
    }
    Ok(())
}

/// Renders a duration the way Go's `time.Duration` prints it, so the
/// "no devices found within 2s" line matches go-udap byte for byte.
///
/// Mirrors the algorithm behind Go's `time.Duration.String()`: below one
/// second, print milliseconds; at or above one second, normalize into
/// h/m/s components (a present larger unit forces the smaller ones to
/// print even when zero, e.g. `2m0s`, `1h0m0s`) and trim any leftover
/// sub-second remainder to a fraction with no trailing zeros (`1.5s`).
///
/// Scoped to what `cli::parse_duration` can actually produce: a
/// non-negative whole number of milliseconds (built from integer
/// ms/s/m CLI input). Go's sub-millisecond units (µs, ns) and negative
/// durations are intentionally not handled — no reachable CLI input
/// produces them, and `std::time::Duration` cannot be negative.
fn format_duration(d: Duration) -> String {
    let total_ms = d.as_millis();
    if total_ms == 0 {
        return "0s".to_owned();
    }
    if total_ms < 1_000 {
        return format!("{total_ms}ms");
    }

    let total_secs = total_ms / 1_000;
    let seconds_part = format!(
        "{}{}s",
        total_secs % 60,
        fractional_suffix(total_ms % 1_000)
    );

    let total_minutes = total_secs / 60;
    if total_minutes == 0 {
        return seconds_part;
    }

    let hours = total_minutes / 60;
    if hours == 0 {
        return format!("{}m{seconds_part}", total_minutes % 60);
    }
    format!("{hours}h{}m{seconds_part}", total_minutes % 60)
}

/// Renders a sub-second millisecond remainder (0..1000) as a
/// decimal-point-prefixed fraction with trailing zeros trimmed, or as
/// an empty string when there is no remainder — matching how Go's
/// `fmtFrac` elides the fraction entirely when it is zero.
fn fractional_suffix(remainder_ms: u128) -> String {
    if remainder_ms == 0 {
        return String::new();
    }
    let digits = format!("{remainder_ms:03}");
    let trimmed = digits.trim_end_matches('0');
    format!(".{trimmed}")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Expected values are Go's own `time.Duration.String()` output,
    /// generated by running a small Go program over the same inputs
    /// (see the task-9-report.md fix-round-1 section for the program
    /// and its output) — not hand-derived.
    #[test]
    fn formats_durations_like_go() {
        assert_eq!(format_duration(Duration::from_millis(0)), "0s");
        assert_eq!(format_duration(Duration::from_millis(1)), "1ms");
        assert_eq!(format_duration(Duration::from_millis(50)), "50ms");
        assert_eq!(format_duration(Duration::from_millis(999)), "999ms");
        assert_eq!(format_duration(Duration::from_millis(1_000)), "1s");
        assert_eq!(format_duration(Duration::from_millis(1_500)), "1.5s");
        assert_eq!(format_duration(Duration::from_secs(2)), "2s");
        assert_eq!(format_duration(Duration::from_secs(59)), "59s");
        assert_eq!(format_duration(Duration::from_secs(60)), "1m0s");
        assert_eq!(format_duration(Duration::from_secs(90)), "1m30s");
        assert_eq!(format_duration(Duration::from_millis(90_500)), "1m30.5s");
        assert_eq!(format_duration(Duration::from_secs(120)), "2m0s");
        assert_eq!(format_duration(Duration::from_secs(3_600)), "1h0m0s");
        assert_eq!(format_duration(Duration::from_secs(3_661)), "1h1m1s");
        // --timeout 2m parses to Duration::from_secs(120) via cli::parse_duration
        // (2 * 60 seconds), same value as the 3rd case above, restated for
        // traceability back to the CLI input that produces it.
        assert_eq!(format_duration(Duration::from_secs(120)), "2m0s");
    }
}
