//! The `discover` subcommand.

use crate::{CliError, ClientFactory};
use go_duration::GoDuration;
use std::io::Write;
use std::time::Duration;
use tokio_util::sync::CancellationToken;

/// Discovers devices and prints one MAC per line.
///
/// Finding nothing is not an error: a note goes to stderr and the exit
/// code stays 0, matching go-udap.
///
/// # Errors
/// [`CliError`] with code 2 if the client cannot be built or discovery fails.
pub async fn run(
    make_client: ClientFactory,
    timeout: GoDuration,
    stdout: &mut dyn Write,
    stderr: &mut dyn Write,
) -> Result<(), CliError> {
    let mut client = make_client().map_err(|e| CliError { code: 2, source: e })?;

    let cancel = CancellationToken::new();
    let token = cancel.clone();
    let wait = wait_duration(timeout);
    tokio::spawn(async move {
        tokio::time::sleep(wait).await;
        token.cancel();
    });

    client.discover(&cancel).await.map_err(|e| CliError {
        code: 2,
        source: anyhow::Error::new(e).context("discovery failed"),
    })?;

    let devices = client.devices();
    if devices.is_empty() {
        // `GoDuration`'s Display *is* Go's `time.Duration.String()`, which is
        // what go-udap prints here:
        // `Fprintf(stderr, "no devices found within %s\n", timeout)`
        // at cli/discover.go:64.
        let _ = writeln!(stderr, "no devices found within {timeout}");
        return Ok(());
    }
    for device in devices {
        let _ = writeln!(stdout, "{}", device.mac);
    }
    Ok(())
}

/// The wall-clock wait for `timeout`.
///
/// `time.ParseDuration` accepts negatives and go-udap does not reject them,
/// so the flag can hold one. Go's `context.WithTimeout` treats a negative as
/// a deadline already in the past — discovery ends immediately rather than
/// erroring — and clamping at zero reproduces that, since
/// `std::time::Duration` is unsigned. The flag's own signed value is still
/// what gets printed.
fn wait_duration(timeout: GoDuration) -> Duration {
    Duration::from_nanos(u64::try_from(timeout.nanoseconds()).unwrap_or(0))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ms(millis: i64) -> GoDuration {
        GoDuration::from(millis * 1_000_000)
    }

    /// Expected values are Go's own `time.Duration.String()` output,
    /// generated by running a small Go program over the same inputs — not
    /// hand-derived.
    ///
    /// The formatting is `go-duration`'s, but the contract is ours: this is
    /// the "no devices found within X" line in the fidelity contract, so a
    /// behaviour change in that crate has to fail here rather than diverge
    /// silently. Every case below was verified against the crate before it
    /// was adopted.
    #[test]
    fn formats_durations_like_go() {
        assert_eq!(ms(0).to_string(), "0s");
        assert_eq!(ms(1).to_string(), "1ms");
        assert_eq!(ms(50).to_string(), "50ms");
        assert_eq!(ms(999).to_string(), "999ms");
        assert_eq!(ms(1_000).to_string(), "1s");
        assert_eq!(ms(1_500).to_string(), "1.5s");
        assert_eq!(ms(2_000).to_string(), "2s");
        assert_eq!(ms(59_000).to_string(), "59s");
        assert_eq!(ms(60_000).to_string(), "1m0s");
        assert_eq!(ms(90_000).to_string(), "1m30s");
        assert_eq!(ms(90_500).to_string(), "1m30.5s");
        assert_eq!(ms(120_000).to_string(), "2m0s");
        assert_eq!(ms(3_600_000).to_string(), "1h0m0s");
        assert_eq!(ms(3_661_000).to_string(), "1h1m1s");
    }

    #[test]
    fn wait_matches_the_timeout() {
        assert_eq!(wait_duration(ms(2_000)), Duration::from_secs(2));
        assert_eq!(wait_duration(ms(50)), Duration::from_millis(50));
    }

    // A negative deadline is already expired, so discovery ends at once.
    #[test]
    fn negative_timeouts_wait_no_time_at_all() {
        assert_eq!(wait_duration(ms(-5_000)), Duration::ZERO);
    }
}
